In [9]:
from bs4 import BeautifulSoup
import requests
import time
import pandas as pd

## CITIES

In [10]:
cities = [
    'helsinki','espoo','tampere','vantaa','oulu','turku','kotka','lahti','kuopio','pori','kouvola',
    'joensuu','lappeenranta','mikkeli','vaasa', # 15
    'rovaniemi','kemi','tornio','savonlinna','nokia' # 20
]
short_list = ['nokia','rovaniemi','kemi','savonlinna','tornio']

## CODE

In [11]:
def get_distance(from_city, to_city):
    query = requests.get('https://www.distancecalculator.net/from-{}-to-{}'.format(from_city, to_city))
    soup = BeautifulSoup(query.text, 'html.parser')
    
    for option in soup.find_all('span'):
        if option.get('id') == 'distance-km':
            return int(option.text[:-3])
        
def create_matrix(cities, csv_name, cooldown_time):
    result = []
    
    # LOOP THROUGH EACH CITY
    for from_city in cities:
        sub_result = []
        
        print(f"getting distances for city: {from_city}...")
        
        # LOOP THROUGH EACH CITY AGAIN
        for to_city in cities:
            
            # APPEND ZERO IF CITIES ARE THE SAME
            if (from_city == to_city):
                sub_result.append(0)
                
            # OTHERWISE, SCRAPE DISTANCE
            else:
                distance = get_distance(from_city, to_city)
                sub_result.append(distance)
                
                # SLEEP FOR 5 SECONDS
                time.sleep(cooldown_time)
            
        # APPEND TO PARENT CONTAINER
        result.append(sub_result)
    
    # CONVERT TO DATAFRAME
    dataframe = pd.DataFrame(result, columns=cities, index=cities)
    
    # SAVE DATAFRAME AS CSV
    dataframe.to_csv(csv_name, index=False)
    print('done!')
    
    return result

## FETCHING DATA

In [12]:
data = create_matrix(cities, 'dt_20.csv', 1)
#data = create_matrix(short_list, 'test.csv', 1)

getting distances for city: helsinki...
getting distances for city: espoo...
getting distances for city: tampere...
getting distances for city: vantaa...
getting distances for city: oulu...
getting distances for city: turku...
getting distances for city: kotka...
getting distances for city: lahti...
getting distances for city: kuopio...
getting distances for city: pori...
getting distances for city: kouvola...
getting distances for city: joensuu...
getting distances for city: lappeenranta...
getting distances for city: mikkeli...
getting distances for city: vaasa...
getting distances for city: rovaniemi...
getting distances for city: kemi...
getting distances for city: tornio...
getting distances for city: savonlinna...
getting distances for city: nokia...
done!

## VALIDATING DATA

In [13]:
dataframe1 = pd.DataFrame(data, columns=cities,index=cities)
#dataframe1 = pd.DataFrame(data, columns=short_list,index=short_list)
dataframe1

,helsinki,espoo,tampere,vantaa,oulu,turku,kotka,lahti,kuopio,pori,kouvola,joensuu,lappeenranta,mikkeli,vaasa,rovaniemi,kemi,tornio,savonlinna,nokia
helsinki,0,16,160,15,539,150,114,99,336,225,124,373,203,211,370,705,619,633,284,164
espoo,16,0,151,24,536,134,128,103,339,211,134,381,215,217,359,702,615,628,293,154
tampere,160,151,0,150,400,142,204,116,254,106,171,335,240,186,210,564,473,484,272,16
vantaa,15,24,150,0,525,153,105,84,321,220,111,359,191,196,360,691,606,619,271,155
oulu,539,536,400,525,0,533,511,448,259,433,465,341,460,380,284,166,91,111,388,406
turku,150,134,142,153,533,0,255,194,394,118,246,463,328,302,296,694,599,607,388,131
kotka,114,128,204,105,511,255,0,89,273,299,46,281,95,137,404,673,598,614,188,215
lahti,99,103,116,84,448,194,89,0,237,215,58,281,136,116,316,613,531,546,198,128
kuopio,336,339,254,321,259,394,273,237,0,343,231,111,206,135,307,412,350,370,129,268
pori,225,211,106,220,433,118,299,215,343,0,272,434,345,291,180,590,492,499,377,91
kouvola,124,134,171,111,465,246,46,58,231,272,0,251,83,96,363,628,552,568,161,184
joensuu,373,381,335,359,341,463,281,281,111,434,251,0,190,164,417,474,430,451,93,350
lappeenranta,203,215,240,191,460,328,95,136,206,345,83,190,0,85,410,617,550,569,97,255
mikkeli,211,217,186,196,380,302,137,116,135,291,96,164,85,0,331,540,469,487,87,201
vaasa,370,359,210,360,284,296,404,316,307,180,363,417,410,331,0,425,326,329,397,206
rovaniemi,705,702,564,691,166,694,673,613,412,590,628,474,617,540,425,0,100,101,537,570
kemi,619,615,473,606,91,599,598,531,350,492,552,430,550,469,326,100,0,23,479,478
tornio,633,628,484,619,111,607,614,546,370,499,568,451,569,487,329,101,23,0,499,488
savonlinna,284,293,272,271,388,388,188,198,129,377,161,93,97,87,397,537,479,499,0,287
nokia,164,154,16,155,406,131,215,128,268,91,184,350,255,201,206,570,478,488,287,0